### ISSUE TITLE
Potentially malicious resources

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-curriculum/phase-1-javascript-project-mode#11]
### Canvas Link

https://learning.flatironschool.com/courses/4330/pages/flex-phase-1-project-review-guidelines?module_item_id=339412

### Concern

Some of the APIs we're suggesting [here](https://github.com/learn-co-curriculum/phase-1-javascript-project-mode#resources) don't seem legitimate
I had a student click an itunes link and it downloaded a file

**Comment by lizbur10** [comment]
Closing this per our conversation in Slack
